# Data analysis with NC DINOS player NC 다이노스 선수 데이터 분석

In [1]:
import pandas as pd

## 1. 데이터 적재 및 통합

In [4]:
nc_data = pd.read_excel('data/NC DINOS.xlsx')

nc_data

,Unnamed: 0,선수명,팀명,경기,타석,타수,안타,홈런,득점,타점,볼넷,삼진,도루,BABIP,타율,출루율,장타율,OPS,wOBA,WAR
0,0,모창민,NC,108,436,395,109,12,57,51,37,68,16,0.307,0.276,0.339,0.443,0.782,0.353,2.31
1,1,이호준,NC,126,508,442,123,20,46,87,60,109,2,0.324,0.278,0.362,0.475,0.837,0.373,1.85
2,2,김종호,NC,128,546,465,129,0,72,22,57,100,50,0.352,0.277,0.376,0.333,0.709,0.339,1.55
3,3,나성범,NC,104,458,404,98,14,55,64,33,95,12,0.279,0.243,0.319,0.416,0.735,0.329,1.50
4,4,조영훈,NC,120,426,380,107,6,38,39,39,56,4,0.316,0.282,0.350,0.413,0.763,0.348,0.83
5,5,이현곤,NC,91,161,139,38,0,10,9,16,14,2,0.304,0.273,0.361,0.324,0.685,0.327,0.52
6,6,이상호,NC,102,138,125,31,0,26,13,9,21,24,0.298,0.248,0.299,0.320,0.619,0.289,0.16
7,7,강진성,NC,3,3,2,1,0,1,0,1,0,0,0.500,0.500,0.667,1.000,1.667,0.671,0.10
8,8,조평호,NC,26,86,79,21,2,12,7,6,24,1,0.358,0.266,0.318,0.418,0.736,0.329,0.09
9,9,박민우,NC,32,48,42,11,0,10,6,5,7,9,0.306,0.262,0.333,0.286,0.619,0.296,0.07
10,10,박정준,NC,77,195,167,41,4,24,21,23,44,4,0.303,0.246,0.335,0.353,0.688,0.320,0.06
11,11,이승호,NC,2,1,0,0,0,0,0,1,0,1,-,-,1.000,-,-,0.712,0.06
12,12,마낙길,NC,24,31,29,9,0,5,0,1,5,2,0.375,0.310,0.333,0.345,0.678,0.317,-0.03
13,13,김성욱,NC,4,4,4,1,0,0,1,0,2,0,0.500,0.250,0.250,0.250,0.500,0.234,-0.03
14,14,강구성,NC,2,2,2,0,0,0,0,0,0,0,0.000,0.000,0.000,0.000,0.000,0.000,-0.06
15,15,지석훈,NC,104,356,309,68,3,25,35,30,82,2,0.285,0.220,0.300,0.330,0.630,0.293,-0.09
16,16,김종찬,NC,5,7,7,1,0,0,0,0,3,0,0.250,0.143,0.143,0.143,0.286,0.134,-0.11
17,17,차화준,NC,58,121,106,24,1,18,7,12,29,4,0.295,0.226,0.306,0.311,0.617,0.289,-0.12
18,18,김동건,NC,7,17,16,2,1,1,1,1,7,0,0.125,0.125,0.176,0.313,0.489,0.216,-0.14
19,19,이창섭,NC,5,5,5,0,0,0,0,0,2,0,0.000,0.000,0.000,0.000,0.000,0.000,-0.14