# Data analysis with NC DINOS player NC 다이노스 선수 데이터 분석

In [1]:
import pandas as pd

### 1. 데이터 적재 및 통합

In [5]:
# excel file loading: pd.read_excel('file path')
# optional parameter 'sheet_name=None` > 전체 sheet loading

nc_data = pd.read_excel('data/NC DINOS.xlsx', sheet_name=None)

nc_data

{'2013':     Unnamed: 0  선수명  팀명   경기   타석   타수   안타  홈런  득점  타점  볼넷   삼진  도루  BABIP  \
 0            0  모창민  NC  108  436  395  109  12  57  51  37   68  16  0.307
 1            1  이호준  NC  126  508  442  123  20  46  87  60  109   2  0.324
 2            2  김종호  NC  128  546  465  129   0  72  22  57  100  50  0.352
 3            3  나성범  NC  104  458  404   98  14  55  64  33   95  12  0.279
 4            4  조영훈  NC  120  426  380  107   6  38  39  39   56   4  0.316
 5            5  이현곤  NC   91  161  139   38   0  10   9  16   14   2  0.304
 6            6  이상호  NC  102  138  125   31   0  26  13   9   21  24  0.298
 7            7  강진성  NC    3    3    2    1   0   1   0   1    0   0  0.500
 8            8  조평호  NC   26   86   79   21   2  12   7   6   24   1  0.358
 9            9  박민우  NC   32   48   42   11   0  10   6   5    7   9  0.306
 10          10  박정준  NC   77  195  167   41   4  24  21  23   44   4  0.303
 11          11  이승호  NC    2    1    0    0   0   0   0   1    0   1      -
 12          12  마낙길  NC   24   31   29    9   0   5   0   1    5   2  0.375
 13          13  김성욱  NC    4    4    4    1   0   0   1   0    2   0  0.500
 14          14  강구성  NC    2    2    2    0   0   0   0   0    0   0  0.000
 15          15  지석훈  NC  104  356  309   68   3  25  35  30   82   2  0.285
 16          16  김종찬  NC    5    7    7    1   0   0   0   0    3   0  0.250
 17          17  차화준  NC   58  121  106   24   1  18   7  12   29   4  0.295
 18          18  김동건  NC    7   17   16    2   1   1   1   1    7   0  0.125
 19          19  이창섭  NC    5    5    5    0   0   0   0   0    2   0  0.000

        타율    출루율    장타율    OPS   wOBA   WAR
 0   0.276  0.339  0.443  0.782  0.353  2.31
 1   0.278  0.362  0.475  0.837  0.373  1.85
 2   0.277  0.376  0.333  0.709  0.339  1.55
 3   0.243  0.319  0.416  0.735  0.329  1.50
 4   0.282  0.350  0.413  0.763  0.348  0.83
 5   0.273  0.361  0.324  0.685  0.327  0.52
 6   0.248  0.299  0.320  0.619  0.289  0.16
 7   0.500  0.667  1.000  1.667  0.671  0.10
 8   0.266  0.318  0.418  0.736  0.329  0.09
 9   0.262  0.333  0.286  0.619  0.296  0.07
 10  0.246  0.335  0.353  0.688  0.320  0.06
 11      -  1.000      -      -  0.712  0.06
 12  0.310  0.333  0.345  0.678  0.317 -0.03
 13  0.250  0.250  0.250  0.500  0.234 -0.03
 14  0.000  0.000  0.000  0.000  0.000 -0.06
 15  0.220  0.300  0.330  0.630  0.293 -0.09
 16  0.143  0.143  0.143  0.286  0.134 -0.11
 17  0.226  0.306  0.311  0.617  0.289 -0.12
 18  0.125  0.176  0.313  0.489  0.216 -0.14
 19  0.000  0.000  0.000  0.000  0.000 -0.14  ,
 '2014':     Unnamed: 0   선수명  팀명   경기   타석   타수   안타  홈런  득점   타점  볼넷   삼진  도루  BABIP  \
 0            0   테임즈  NC  125  514  443  152  37  95  121  58   99  11  0.367
 1            1   나성범  NC  123  536  477  157  30  88  101  43  128  14  0.397
 2            2   박민우  NC  118  491  416  124   1  87   40  56   89  50  0.373
 3            3   손시헌  NC   97  361  307   90   5  39   39  34   53   2  0.331
 4            4   지석훈  NC  114  238  212   58   6  26   34  16   46   1  0.323
 5            5   이호준  NC  122  500  424  115  23  59   78  67  104   2  0.305
 6            6   권희동  NC  101  252  221   63   7  39   36  25   43   6  0.324
 7            7   모창민  NC  122  468  419  110  16  62   72  37   82  14  0.289
 8            8   이종욱  NC  124  495  438  126   6  73   79  40   60  15  0.313
 9            9   김준완  NC    6    5    4    2   0   1    0   1    1   1  0.667
 10          10   최재원  NC    2    2    1    0   0   1    0   1    1   0      -
 11          11   마낙길  NC    2    2    1    0   0   1    0   1    0   0  0.000
 12          12   조영훈  NC   92  124  111   29   6  15   22  10   26   1  0.288
 13          13   김태우  NC    4    5    5    1   0   0    0   0    3   0  0.500
 14          14  박명환*  NC    2    1    1    0   0   0    0   0    1   0      -
 15          15   조평호  NC    2    2    2    0   0   0    0   0    0   0  0.000
 16          16   강민국  NC    6    3    3    0   0   0    0   0    0   0  0.000
 17          17    허준  NC   28   36   29    5   0   2    1   5   10   0  0.263
 18          18   김성욱  NC   26   26   23    4   1   6    1   3    9   1  0.231
 19          19   노진혁  NC   25   16   16    3   1   3    2   0    7   0  0.250

        타율    출루율    장타율    OPS   wOBA   WAR
 0   0.343  0.422  0.688  1.110  0.456  6.36
 1   0.329  0.400  0.597  0.997  0.424  5.94
 2   0.298  0.392  0.399  0.791  0.365  2.73
 3   0.293  0.368  0.414  0.782  0.349  1.52
 4   0.274  0.340  0.462  0.802  0.352  0.97
 5   0.271  0.371  0.481  0.852  0.369  0.88
 6   0.285  0.363  0.443  0.806  0.353  0.62
 7   0.263  0.320  0.413  0.733  0.319  0.17
 8   0.288  0.343  0.411  0.754  0.332  0.13
 9   0.500  0.600  0.500  1.100  0.509  0.11
 10  0.000  0.500  0.000  0.500  0.363  0.01
 11  0.000  0.500  0.000  0.500  0.363  0.01
 12  0.261  0.325  0.459  0.784  0.337 -0.02
 13  0.200  0.200  0.400  0.600  0.244 -0.03
 14  0.000  0.000  0.000  0.000  0.000 -0.03
 15  0.000  0.000  0.000  0.000  0.000 -0.07
 16  0.000  0.000  0.000  0.000  0.000 -0.10
 17  0.172  0.294  0.276  0.570  0.268 -0.11
 18  0.174  0.269  0.348  0.617  0.272 -0.15
 19  0.188  0.188  0.375  0.563  0.231 -0.18  ,
 '2015':     Unnamed: 0  선수명  팀명   경기   타석   타수   안타  홈런   득점   타점   볼넷   삼진  도루  \
 0            0  테임즈  NC  142  595  472  180  47  130  140  103   91  40
 1            1  나성범  NC  144  622  564  184  28  112  135   33  127  23
 2            2  박민우  NC  141  617  520  158   3  111   47   73  108  46
 3            3  이호준  NC  131  518  449  132  24   48  110   61  102   0
 4            4  김종호  NC  133  486  424  125   4   90   36   44   65  41
 5            5  조영훈  NC  103  146  124   35   8   20   35   19   36   3
 6            6  손시헌  NC  140  508  440  108  13   56   58   36   66   3
 7            7  이종욱  NC  125  504  440  118   5   63   52   54   78  17
 8            8  모창민  NC  103  239  214   62   6   23   35   18   52   5
 9            9  지석훈  NC  137  466  415  111  11   53   46   23   85   4
 10          10  용덕한  NC   50   49   42   12   0    4    5    5    8   2
 11          11  최재원  NC  114  102   85   21   2   31   13   10   29  14
 12          12  박정준  NC   19   24   21    8   0    2    2    0    5   0
 13          13  김태군  NC  144  474  421  107   6   45   52   25   77   1
 14          14  조평호  NC   22   22   22    8   1    4    3    0    6   0
 15          15  이창섭  NC   15    8    5    0   0    0    0    3    3   0
 16          16  김준완  NC   30   54   44   10   0   12    2   10   10   2
 17          17  강구성  NC    4    5    5    1   0    0    0    0    0   0
 18          18  강민국  NC    1    2    2    0   0    0    0    0    1   0
 19          19  김태진  NC    1    3    3    0   0    0    0    0    0   0

     BABIP     타율    출루율    장타율    OPS   wOBA    WAR
 0   0.390  0.381  0.497  0.790  1.287  0.520  11.73
 1   0.374  0.326  0.373  0.553  0.926  0.390   4.46
 2   0.373  0.304  0.399  0.404  0.803  0.364   3.52
 3   0.332  0.294  0.381  0.510  0.891  0.381   2.19
 4   0.338  0.295  0.364  0.394  0.758  0.340   1.03
 5   0.329  0.282  0.372  0.540  0.912  0.389   1.00
 6   0.260  0.245  0.319  0.398  0.717  0.316   0.85
 7   0.315  0.268  0.351  0.368  0.719  0.322   0.84
 8   0.352  0.290  0.340  0.439  0.779  0.340   0.76
 9   0.311  0.267  0.328  0.383  0.711  0.317   0.51
 10  0.353  0.286  0.375  0.310  0.685  0.326   0.44
 11  0.352  0.247  0.366  0.412  0.778  0.350   0.30
 12  0.500  0.381  0.458  0.476  0.934  0.417   0.25
 13  0.293  0.254  0.307  0.354  0.661  0.294   0.25
 14  0.467  0.364  0.364  0.591  0.955  0.401   0.18
 15  0.000  0.000  0.375  0.000  0.375  0.286  -0.01
 16  0.294  0.227  0.370  0.227  0.597  0.308  -0.04
 17  0.200  0.200  0.200  0.400  0.600  0.242  -0.04
 18  0.000  0.000  0.000  0.000  0.000  0.000  -0.06
 19  0.000  0.000  0.000  0.000  0.000  0.000  -0.09  }

In [11]:
# sheet별 data를 각각 개별 변수에 저장
nc_13, nc_14, nc_15 = nc_data.values()

In [12]:
# 같은 shape의 data
print(nc_13.shape)
print(nc_14.shape)
print(nc_15.shape)

(20, 20)
(20, 20)
(20, 20)

In [13]:
nc_13.index

RangeIndex(start=0, stop=20, step=1)

In [14]:
nc_13.columns

Index(['Unnamed: 0', '선수명', '팀명', '경기', '타석', '타수', '안타', '홈런', '득점', '타점',
       '볼넷', '삼진', '도루', 'BABIP', '타율', '출루율', '장타율', 'OPS', 'wOBA', 'WAR'],
      dtype='object')

In [16]:
# 상위 2개 인덱스
nc_15.head(2)

,Unnamed: 0,선수명,팀명,경기,타석,타수,안타,홈런,득점,타점,볼넷,삼진,도루,BABIP,타율,출루율,장타율,OPS,wOBA,WAR
0,0,테임즈,NC,142,595,472,180,47,130,140,103,91,40,0.390,0.381,0.497,0.790,1.287,0.52,11.73
1,1,나성범,NC,144,622,564,184,28,112,135,33,127,23,0.374,0.326,0.373,0.553,0.926,0.39,4.46

In [25]:
# nc_N data 'Unnamed: 0' column delete

nc_year_data = [nc_13, nc_14, nc_15]

for data in nc_year_data:
    data.drop('Unnamed: 0', axis=1)
    # == del data['Unnamed: 0']

In [30]:
# '선수명' columns 이용 > 'nc_13'동명이인이 있는지 여부, 선수명 수 출력
# `.unique()`: 중복값 배제, show 내부 data

print(nc_13['선수명'].count())
print(len(nc_13['선수명'].unique()))

20
20

In [33]:
# 전체년도 동명이인 여부

for data in nc_year_data:
    if data['선수명'].count() != len(data['선수명'].unique()):
        print(True)
    else:
        print(False)

False
False
False

In [35]:
# set data type > 내부 중복 data > item 1개로 간주
# `set()` > 여러 년도 선수 확인 가능
# 13, 14, 15년 선수 수=20 동일
# 14, 15년 연속 주전이었던 선수의 인원 수

len(set(nc_14.선수명.unique()) & set(nc_15['선수명'].unique()))

13